### ISSUE TITLE
Safari: Can't make new edges in visual editor

### ISSUE THREAD

**Issue by bakkot** [precup/turing-machine-sim#106]
The arrows do not appear, preventing the creation of edges.

**Comment by precup** [comment]
What Safari version are you using?

**Comment by maxwang7** [comment]
I just checked on my Safari, it's working. Version 8.0.4 (10600.4.10.7).

**Comment by maxwang7** [comment]
Ah, tested on cluster computers, doesn't work. Version 7.0.6 (9537.78.2)

**Comment by maxwang7** [comment]
More testing:
The problem is not that you can't make new edges, it's that edge previewing doesn't work. I can drag from one node to another and create an edge.

Also, there are no console messages aside from "hi Jay" every time I click on a node.

**Comment by maxwang7** [comment]
Another follow-up:
The edge previewing works after clicking a node and then clicking "set as start".
