### ISSUE TITLE
epsilon should not be a part of Sigma

### ISSUE THREAD

**Issue by bakkot** [precup/turing-machine-sim#109]
When making an NFA, if you create an edge with all characters and epsilon, it just displays Sigma. If you do all characters without epsilon, it displays Sigma - epsilon. But epsilon is definitionally not a letter in the alphabet, ie, is not contained in Sigma.

**Comment by precup** [comment]
Alright, I changed the way it displays, reassigning this to Jay to give it a once over on the actual notation I used. Kevin, if you feel like chiming in, feel free.

**Comment by moonj** [comment]
Current notation works for me. Sigma + epsilon makes sense. Also, alphabet bar still displays epsilon as an alphabet character?
