### ISSUE TITLE
Unclear what blue circle is for

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#123]
Brendon didn't realize that the blue circle was for testing interface

**Comment by moonj** [comment]
![screen-shot-2015-05-08-at-10 23 35-pm](https://cloud.githubusercontent.com/assets/1813243/7548861/75ca22e0-f5d1-11e4-8d17-72a918a46f77.png)

this is dumb but hey

**Comment by maxwang7** [comment]
Looks good to me!
