### ISSUE TITLE
Change original color of bottom string entry for testing

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#124]
it was confusing at first when the bottom black string area had the grid, want intuitive that text should be entered there

**Comment by moonj** [comment]
is this too dumb of a solution

![screen-shot-2015-05-08-at-10 20 34-pm](https://cloud.githubusercontent.com/assets/1813243/7548839/bed61486-f5d0-11e4-9f53-0f27371db18a.png)

**Comment by maxwang7** [comment]
@moonj Fine by me, and I'll take this issue

**Comment by maxwang7** [comment]
We need to find a better solution.

**Comment by moonj** [comment]
![bed61486-f5d0-11e4-9f53-0f27371db18a](https://cloud.githubusercontent.com/assets/1813243/7695688/1bfa3596-fda8-11e4-85ca-0530fc050c97.png)
