### ISSUE TITLE
"removing character that aren't in alphabet" error message appears multiple times (ss2)

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#126]
"removing character that aren't in alphabet" error message appears multiple times
![screenshot 2015-05-06 01 06 14](https://cloud.githubusercontent.com/assets/5680188/7489796/940d7a20-f38f-11e4-8285-b7b61a994e66.png)

**Comment by precup** [comment]
Can't repro, can you provide more information?

**Comment by maxwang7** [comment]
I've asked Brendon to see if he can reproduce it, as I haven't been able to.

**Comment by maxwang7** [comment]
Brendon:

"i think you guys fixed it already"

"i can't make it happen either"
