### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#127]
maybe differentiate save and save as? - a little unintuitive right now
update saved name url after saving

**Comment by maxwang7** [comment]
Do we want to differentiate "Save" and "Save As" as two different buttons? "Save" would just be a shortcut for "Save As" with the same current name, if there is one, without a message for overwriting.

**Comment by moonj** [comment]
I like that solution. Pretty much what every software with saving currently does.

Only have the two different buttons appear after the first save though, or at least disable the "Save" button.

**Comment by maxwang7** [comment]
Ok, sounds good! Also, in the future, please reassign me once you answer.

**Comment by maxwang7** [comment]
@moonj Should we also place the name of the current automata somewhere?

**Comment by maxwang7** [comment]
Jay said to place it in .alphabet-bar (just above the tape)
