### ISSUE TITLE
Automatically set a default start state?

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#128]
Brendon clicked "run" many times and got the "no initial start state" error message. This could help save frustration. Does it have the potential to make the user not realize where the start state is set.

**Comment by precup** [comment]
Eh, we have a 1/n chance of actually getting it right, if it starts running with a random start state and the output isn't what the student expected, they're unlikely to realize it's because we added a start state.

Jay, thoughts?

**Comment by moonj** [comment]
https://github.com/precup/turing-machine-sim/issues/129

**Comment by maxwang7** [comment]
Looks good, as #129 fixed this too

**Comment by precup** [comment]
#129 didn't fix this
