### ISSUE TITLE
IMPORTANT! Double click to create node unintuitive

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#129]
Brendon only figured it out after creating his solution.

**Comment by moonj** [comment]
We could start all problems with an empty canvas, and do this:

![screen shot 2015-05-08 at 10 09 59 pm](https://cloud.githubusercontent.com/assets/1813243/7548803/3b07aa80-f5cf-11e4-8a5c-8df24ba648dd.png)

This first node will also probably be what people will make their start node, so we can just auto-set that to be the start and kill two birds with one stone.
