### ISSUE TITLE
can save but can't load a name with &

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#134]

**Comment by precup** [comment]
We'll want to use encodeURIComponent and decodeURIComponent. I'm assigning this to Max since it's primarily in the server code.

**Comment by maxwang7** [comment]
@precup, please confirm that this bug has been fixed correctly. Thanks!

**Comment by precup** [comment]
Saving and then loading !@#$%^&*() on restricted_copy fails for me.

**Comment by maxwang7** [comment]
Oh wow, I did not try out those characters, nice.

**Comment by maxwang7** [comment]
Oh wait, I'm running on restricted

**Comment by maxwang7** [comment]
Confirmed by @precup, closed
