### ISSUE TITLE
allow user to hit enter in modals

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#135]

**Comment by precup** [comment]
This already works for me, what browser is this not working in?

**Comment by maxwang7** [comment]
Just did more testing. Both Safari and Chrome: it only works on the node and edge editing modals, not the save, load, or submit modals. Also, on the node and edge editing modals, I need to be focused on one of the input elements for hitting "enter" to work -- I think hitting enter in a modal, no matter what element is focused, should be counted as a "submit".
