### ISSUE TITLE
display the problem number and pset number

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#136]

**Comment by moonj** [comment]
Mockup had this on the top-left corner but I'm not sure if the space is there on smaller screens. How do you guys feel about putting it in .alphabet-bar?

![screen shot 2015-05-08 at 9 55 27 pm](https://cloud.githubusercontent.com/assets/1813243/7548760/f8723552-f5cc-11e4-9625-c3e1319e67e8.png)

**Comment by precup** [comment]
I don't have a problem with it

**Comment by maxwang7** [comment]
@precup but do you see a pset?
