### ISSUE TITLE
"Save failed" error message is not very descriptive, and should not disappear until the popup is closed.

### ISSUE THREAD

**Issue by precup** [precup/turing-machine-sim#142]

**Comment by maxwang7** [comment]
What would be a better wording for the error message? "Server could not be reached"? Or "You may not be connected to the Internet"?

**Comment by moonj** [comment]
Save failed: couldn't connect to server.

should be fine.

**Comment by maxwang7** [comment]
As of a248759d92797c9422ae4567e298a36cc54f8a9c, this is fixed.
