### ISSUE TITLE
Testing bar should highlight current character

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#37]
From Kevin:

The testing bar at the bottom highlights the character it's going to process next. This is a bit pedantic, but I would expect a highlighted character to be one which is currently being processed (so maybe highlighting an edge? not that this is an important feature), not one which is about to be processed. I think it's a lot clearer to have the cursor being between characters rather than over a particular one.

**Comment by precup** [comment]
Assigned to Jay since he'd need to design something for this, then I can implement it.
